Dodana mogucnost specificiranja verzije do koje ce se raditi update/downgrade

diff --git a/dbdowngrade b/dbdowngrade
--- a/dbdowngrade
+++ b/dbdowngrade
@@ -1,16 +1,19 @@
 #!/bin/bash
 
 if [ -z "${1}" ] || [ "${1}" = "--help" ]; then
- echo "usage: ${0} [PATH] [--demo] [--full] mysql_params db_name"
+ echo "usage: ${0} [PATH] [--demo] [[--full]|[--ver XYZ]]? mysql_params db_name"
  echo
  echo " PATH         - path containing .SQL upgrade files, '.' by default"
- echo " --demo       - use additional .SQL scripts to fill db with demo data"
+ echo " --demo       - use additional .SQL scripts to delete demo data"
  echo " --full       - execute all UP*.SQL scripts upto the latest version"
+ echo " --ver XYZ    - downgrade to version specified by XYZ, can't combine with --full"
  echo " mysql_params - parameters to connect to database, as given to mysql client"
  echo " db_name      - name of the database to update"
  echo
  exit 0
 fi
+
+VERSION_LENGTH=3
 
 SQLPATH=
 if [[ -d ${1} ]]; then
@@ -30,6 +33,31 @@ if [ ${1} = "--full" ]; then
  shift
 fi
 
+TVER=""
+if [ ${1} = "--ver" ]; then
+ shift
+ TVER=${1}
+ ACTUAL_LENGTH=${#TVER}
+ if [ $ACTUAL_LENGTH -ne $VERSION_LENGTH ]; then
+  echo "${0}: invalid version: expecting three digits, zero-padded to the left"
+  exit 1
+ fi
+ if [[ ! ${TVER} =~ ^[0-9]+$ ]]; then
+  echo "${0}: invalid version: expecting three digits, zero-padded to the left"
+  exit 1
+ fi
+ shift
+fi
+
+if [[ $FULL -eq 1 ]] && [ ! $TVER = "" ]; then
+ echo "${0}: can't combine --full and --ver flags"
+ exit 1
+fi
+
+if [ ! ${TVER} = "" ]; then
+ FULL=1
+fi
+
 DB=${@:$#}
 
 VER=`mysql ${*%${!#}} -e "USE ${DB}; SELECT IF(EXISTS(SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '${DB}'),
@@ -42,6 +70,17 @@ if [ -z "${VER}" ]; then
  exit 1
 fi
 
+if [ "${TVER}" = "${VER}" ]; then
+ echo "${0}: database is already at version ${TVER}: nothing to do"
+ exit 0
+fi
+if [ ! "${TVER}" = "" ]; then
+ if [ "${TVER}" -gt "${VER}" ]; then
+  echo "${0}: specified --ver (${TVER}) is greater than database version (${VER}): exiting"
+  exit 1
+ fi
+fi
+
 MINVER=`mysql ${*%${!#}} -e "USE ${DB}; SELECT IF(EXISTS(SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '${DB}'),
                                                IF(EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '${DB}' AND TABLE_NAME = 'setting'),
                                                IF(((SELECT settingValue FROM setting WHERE settingName = 'minAllowedVersion') IS NULL), '${VER}',
@@ -51,8 +90,15 @@ if [ -z "${MINVER}" ]; then
  MINVER="${VER}"
 fi
 
+if [ ! "${TVER}" = "" ]; then
+ if [ "${TVER}" -lt "${MINVER}" ]; then
+  TVER=""
+  echo "${0}: minimum allowed version is ${MINVER}: ignoring --ver flag"
+ fi
+fi
+
 KEEPON=1
-while [ "${VER}" -gt "${MINVER}" ] && [ "${KEEPON}" -eq 1 ]; do
+while [ "${VER}" -gt "${MINVER}" ] && [ "${KEEPON}" -eq 1 ] && { [ "${TVER}" = "" ] || [ "${TVER}" -lt "${VER}" ]; } do
  if [ ${DEMO} -eq 1 ]; then
   DEMOFILE="${SQLPATH}DEMODEL_${VER}.SQL"
   if [[ -f ${DEMOFILE} ]]; then
@@ -72,4 +118,3 @@ while [ "${VER}" -gt "${MINVER}" ] && [ "${KEEPON}" -eq 1 ]; do
   KEEPON=0
  fi
 done
-
diff --git a/dbupdate b/dbupdate
--- a/dbupdate
+++ b/dbupdate
@@ -1,16 +1,19 @@
 #!/bin/bash
 
 if [ -z "${1}" ] || [ "${1}" = "--help" ]; then
- echo "usage: ${0} [PATH] [--demo] [--full] mysql_params db_name"
+ echo "usage: ${0} [PATH] [--demo] [[--full]|[--ver XYZ]]? mysql_params db_name"
  echo
  echo " PATH         - path containing .SQL upgrade files, '.' by default"
  echo " --demo       - use additional .SQL scripts to fill db with demo data"
  echo " --full       - execute all UP*.SQL scripts upto the latest version"
+ echo " --ver XYZ    - update to version specified by XYZ, can't combine with --full"
  echo " mysql_params - parameters to connect to database, as given to mysql client"
  echo " db_name      - name of the database to update"
  echo
  exit 0
 fi
+
+VERSION_LENGTH=3
 
 SQLPATH=
 if [[ -d ${1} ]]; then
@@ -28,6 +31,31 @@ FULL=0
 if [ ${1} = "--full" ]; then
  FULL=1
  shift
+fi
+
+TVER=""
+if [ ${1} = "--ver" ]; then
+ shift
+ TVER=${1}
+ ACTUAL_LENGTH=${#TVER}
+ if [ $ACTUAL_LENGTH -ne $VERSION_LENGTH ]; then
+  echo "${0}: invalid version: expecting three digits, zero-padded to the left"
+  exit 1
+ fi
+ if [[ ! ${TVER} =~ ^[0-9]+$ ]]; then
+  echo "${0}: invalid version: expecting three digits, zero-padded to the left"
+  exit 1
+ fi
+ shift
+fi
+
+if [[ $FULL -eq 1 ]] && [ ! $TVER = "" ]; then
+ echo "${0}: can't combine --full and --ver flags"
+ exit 1
+fi
+
+if [ ! ${TVER} = "" ]; then
+ FULL=1
 fi
 
 DB=${@:$#}
@@ -55,9 +83,20 @@ if [ -z "${VER}" ]; then
  NOVER=1
 fi
 
+if [ "${TVER}" = "${VER}" ]; then
+ echo "${0}: database is already at version ${TVER}: nothing to do"
+ exit 0
+fi
+if [ ! "${TVER}" = "" ]; then
+ if [ "${TVER}" -lt "${VER}" ]; then
+  echo "${0}: specified --ver (${TVER}) is lower than database version (${VER}): exiting"
+  exit 1
+ fi
+fi
+
 ERR=0
 F=fakefile.sql
-while [ ! -z ${F} ]; do
+while [ ! -z ${F} ] && { [ "${TVER}" = "" ] || [ "${TVER}" -gt "${VER}" ]; } do
  VER="`printf %03g $((10#${VER} + 1))`"
  FILE="${SQLPATH}UP_${VER}_Version_"
  FOUND=0
@@ -71,12 +110,16 @@ while [ ! -z ${F} ]; do
    ERR=$?
    unset NOVER
   fi
-  if [ $ERR -eq 0 ]; then
+  if [ $ERR -eq 0 ] && [ ! -z ${F} ]; then
    echo "$0: Updated database '${DB}' to version ${VER}"
   fi
  done
 
- if [ ${DEMO} -eq 1 ]; then
+ if [ ${FOUND} -eq 0 ] || [ ${FULL} -eq 0 ] || [ ${ERR} -ne 0 ]; then
+  unset F
+ fi
+
+ if [ ${DEMO} -eq 1 ] && [ ! -z ${F} ]; then
   DEMOFILE="${SQLPATH}DEMOPUT_${VER}.SQL"
   if [[ -f ${DEMOFILE} ]]; then
    mysql $@ < "${DEMOFILE}"
@@ -85,16 +128,16 @@ while [ ! -z ${F} ]; do
    else
     echo "$0: Failed applying demo script for version ${VER}."
    fi
-  else
-   echo "$0: There were no demo scripts for version ${VER}."
   fi
- fi
-
- if [ ${FOUND} -eq 0 ] || [ ${FULL} -eq 0 ] || [ ${ERR} -ne 0 ]; then
-  unset F
  fi
 done
 
 if [ ${ERR} -ne 0 ]; then
  echo "$0: There were errors in SQL scripts."
+fi
+
+if [ ! "${TVER}" = "" ]; then
+ if [ "${TVER}" -gt "${VER}" ]; then
+  echo "${0}: no more update files: can't update to specified --ver (${TVER})"
+ fi
 fi
